package testRailSupport;

public class TestRailSetUp {

	
	public static String RunID;
	public static Boolean createNewRun = false;
	public static Boolean postResults = false;
	public String GetAutoGeneratedRunID() {
		// TODO Auto-generated constructor stub
		return RunID;
		
	}

}
